name: Java CI with Maven for Multiple Services

on:
  push:
    branches: ["main"]
    paths:
      - "*/**"
  pull_request:
    branches: ["main"]
    paths:
      - "*/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [11] # Liste des versions JDK à utiliser

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: |
          find . -name pom.xml -not -path "./pom.xml" -exec dirname {} \; | while read dir; do
            echo "Building $dir"
            (cd "$dir" && mvn -B package)
          done
